---
title: Функції 3
---

# Виклик Функції `print()` 
Імʼя функції (`print` в нашому випадку) разом з дужками та можливо аргументами, формують виклик функції.

Ми до цього повернемось трохи пізніше, але варто привідкрити завісу.

``` { .yaml .copy }
print("Hello, World!")
```

Що відбувається коли Python зустрічає такий виклик функції?

`function_name(argument)`

Роздивимось:

- Спершу, Python перевіряє чи вказане імʼя правильне (він дивиться свої записи, щоб зʼясувати чи існує функція з таким імʼям; якщо її не знайдено, Python перериває виконання коду);
- Друге, Python перевіряє вимоги функції щодо числа аргументів і чи такий виклик дозволений (наприклад якщо якась функція вимагає рівно 2 аргументи, будь-який виклик функції з 1 аргументом вважатиметься помилковим, та перерве виконання програми);
- Третє, Python залишає ваш код на мить, щоб виконати код функції, яку ви викликаєте; звісно він бере із собою аргументи, які ви передаєте функції;
- Четверте, функція виконує свій код, призводить до бажаного ефекту (якщо передбачений),обчислює результат (якщо він є) та завершує своє виконання;
- Нарешті, Python повертається до вашого коду (до того самого місця, де відбувся виклик функції) та продовжує виконання вашої програми. 